[package]
name = "rimrs"
description = "RimWorld mod manager"
version = "0.0.1"
edition = "2021"
license = "Unlicense"
homepage = "https://github.com/Breadinator/rimrs"
repository = "https://github.com/Breadinator/rimrs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
eframe = "0.20"
egui_extras = "0.20.0"
env_logger = "0.10.0"
log = "0.4.17"
once_cell = "1.17.0"
open = "3.2"
regex = "1.7.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_ini = "0.2.0"

